# Gitpod configuration for AgentAuth Python Playground

image: python:3.11

tasks:
  - name: Setup and Run
    init: |
      pip install -r requirements.txt
    command: |
      echo "🚀 AgentAuth Python Playground Ready!"
      echo ""
      echo "Run the demo with: python main.py"
      echo ""
      python main.py

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
